#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin";
use TestHelper;

use Test::More;
use File::Temp qw(tempdir);

use lib "$FindBin::Bin/../scripts";
use Spamikaze;

TestHelper::load_named();

# Use a temp dir for zone file output
my $tmpdir = tempdir(CLEANUP => 1);
my $zonefile = "$tmpdir/zone";

# Override the zone file location (converted to 'our' by load_named)
our $dnsbl_location;
$dnsbl_location = $zonefile;

our $zone_header;

# Helper to run main() and return zone file contents
sub generate_zone {
    # Reset the zone_header (it's appended to in build_zone_header)
    $zone_header = '';
    main();
    open my $fh, '<', $zonefile or die "Cannot read $zonefile: $!";
    my $content = do { local $/; <$fh> };
    close $fh;
    return $content;
}

# === Zone header tests ===

# --- SOA record present ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/IN\s+SOA\s+ns1\.example\.com\.\s+root\.ns1\.example\.com\./,
        'SOA record has correct primary NS and admin');
}

# --- Serial is a timestamp ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/(\d{10,})\s*;\s*serial/, 'serial is a unix timestamp');
}

# --- Primary NS record ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/\tIN\tNS\tns1\.example\.com\./, 'primary NS record present');
}

# --- Secondary NS record ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/\tIN\tNS\tns2\.example\.com\./, 'secondary NS record present');
}

# --- Domain A record ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/\tIN\tA\t127\.0\.0\.2/, 'domain A record present');
}

# --- $ORIGIN directive ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/\$ORIGIN\tbl\.example\.com\./, '$ORIGIN set to DNSBL domain');
}

# --- Standard test entry 2.0.0.127 ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/2\.0\.0\.127\tIN\tA\t127\.0\.0\.2/, 'standard test entry present');
    like($zone, qr/IN\tTXT\tbl\.example\.com test entry/, 'test entry TXT record');
}

# --- $TTL directive ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/\$TTL 864000/, '$TTL directive present');
}

# --- Auto-generated comment ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/^; automatically generated by Spamikaze/m, 'auto-generated header comment');
}

# --- Zone completion marker ---
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/; dnsbl file complete/, 'zone completion marker at end');
}

# === Empty blocklist ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    # Should have header and footer but no IP entries between data markers
    like($zone, qr/; dnsbl data starts here\n; dnsbl file complete/,
        'empty blocklist: no entries between data markers');
}

# === Single IP ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('192.168.1.100');
    my $zone = generate_zone();

    # A record with reversed IP
    like($zone, qr/100\.1\.168\.192\t3600\tIN\tA\t\s*127\.0\.0\.2/,
        'single IP: A record with reversed octets and TTL');

    # TXT record with original IP
    like($zone, qr/IN\tTXT\t"http:\/\/example\.com192\.168\.1\.100"/,
        'single IP: TXT record with original IP in URL');
}

# === Multiple IPs ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('10.0.0.1', '172.16.0.2', '203.0.113.99');
    my $zone = generate_zone();

    like($zone, qr/1\.0\.0\.10\t3600\tIN\tA/, 'multi IP: first IP reversed');
    like($zone, qr/2\.0\.16\.172\t3600\tIN\tA/, 'multi IP: second IP reversed');
    like($zone, qr/99\.113\.0\.203\t3600\tIN\tA/, 'multi IP: third IP reversed');

    # All TXT records present
    like($zone, qr/http:\/\/example\.com10\.0\.0\.1/, 'multi IP: first TXT URL');
    like($zone, qr/http:\/\/example\.com172\.16\.0\.2/, 'multi IP: second TXT URL');
    like($zone, qr/http:\/\/example\.com203\.0\.113\.99/, 'multi IP: third TXT URL');
}

# === IP reversal correctness ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('1.2.3.4');
    my $zone = generate_zone();
    like($zone, qr/4\.3\.2\.1\t/, 'IP 1.2.3.4 reversed to 4.3.2.1');
}

{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('255.0.128.1');
    my $zone = generate_zone();
    like($zone, qr/1\.128\.0\.255\t/, 'IP 255.0.128.1 reversed to 1.128.0.255');
}

# === TTL in records matches config ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('10.20.30.40');
    my $zone = generate_zone();
    like($zone, qr/40\.30\.20\.10\t3600\tIN\tA/, 'A record uses configured TTL 3600');
    like($zone, qr/\t\t3600\tIN\tTXT/, 'TXT record uses configured TTL 3600');
}

# === SOA timing values ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    my $zone = generate_zone();
    like($zone, qr/3600\s*;\s*refresh/, 'SOA refresh is 3600');
    like($zone, qr/3600\s*;\s*retry/, 'SOA retry is 3600');
    like($zone, qr/864000\s*;\s*expire/, 'SOA expire is 864000');
    like($zone, qr/3600\s*;\s*negative/, 'SOA negative TTL matches config');
}

# === File atomicity: temp file renamed ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ();
    # Before generating, no leftover temp files should exist
    generate_zone();
    my @temps = glob("$zonefile.*");
    is(scalar @temps, 0, 'no leftover temp files after generation');
    ok(-f $zonefile, 'final zone file exists');
}

# === Record ordering: entries appear after header, before footer ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('198.51.100.1');
    my $zone = generate_zone();
    my $data_start = index($zone, '; dnsbl data starts here');
    my $entry_pos = index($zone, '1.100.51.198');
    my $footer_pos = index($zone, '; dnsbl file complete');
    ok($data_start < $entry_pos, 'entry appears after data start marker');
    ok($entry_pos < $footer_pos, 'entry appears before completion marker');
}

# === A record followed by TXT record for same IP ===
{
    TestHelper::reset_mocks();
    @TestHelper::listed_addresses = ('192.0.2.1');
    my $zone = generate_zone();
    # The A record line should be immediately followed by the TXT record line
    like($zone, qr/1\.2\.0\.192\t3600\tIN\tA\s+127\.0\.0\.2\n\t\t3600\tIN\tTXT\t"http:\/\/example\.com192\.0\.2\.1"/,
        'A record immediately followed by TXT record for same IP');
}

done_testing();
